### Importing and creating numpy array

In [1]:

import numpy as np
a = np.array([1,2,3], dtype= 'int16')
print(a)

a

[1 2 3]


array([1, 2, 3], dtype=int16)

print("Hello world")

In [3]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [4]:
b.ctypes


In [0]:
b.dtype

Finding datatype dtype


In [0]:
a.dtype

Getting array shape details [rows, column]

In [0]:
c = np.array([[[20,21],[22,23]],[[24,25],[26,27]]])
c.shape

Accessing element in 3D array

In [0]:
c[0,0,1]

Creating array with full zeros ([rows, column],datatype)

In [14]:
one = np.zeros([2,2], dtype= 'int32')

In [0]:
one

Creating array with full ones ([rows, column],datatype)

In [21]:
zero = np.ones_like([10])
zeronl = np.ones([2,10], dtype= 'int32')
zeronl

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [23]:
c.ones_like


AttributeError: 'numpy.ndarray' object has no attribute 'ones_like'

In [24]:
c = np.ones_like([2])
c

array([1])

In [0]:
np.ones_like(c)

Creating array with any number syntax:
 numpy.full([rows, cloumn], number)

In [26]:
num = np.full([3,3],100)
num

array([[100, 100, 100],
       [100, 100, 100],
       [100, 100, 100]])

In [0]:
num = np.full_like(num,99)

Creating array with random float B/W 0,1 syntax:
numpy.random.rand(rows, column)

In [0]:
np.random.rand(4,2)

Creating array with Random value syntax:
numpy.random.randint([start:end],size = [rows, cloumn]) 

In [0]:
np.random.randint(7,size = [3,3])

Pratice Code

In [0]:
z = np.zeros([7,7], dtype='int16')
y = np.ones([5,5], dtype = 'int16')
print(z)
y[2,2] = 5
print(y)
z[1:6,1:6] = y
print(z)

Reading data from txt file and creating array with read data seperated by ',' syntax:
numpy.genfromtxt("{filename.extension}", delimiter = "{seperator}")

In [58]:
filedata = np.genfromtxt("Sample_data.txt",delimiter=",")
filedata = filedata.astype('int32')
print(filedata)


[[     1      2      3      2      1      2      1   2121    321   1231
     432]
 [  4234 432432 414124   5325  63562   6324    312    312     31      2
    1231]
 [776344   6543      2     65      0   6340      4   3123   3123   3123
    3121]]
