In [7]:
import numpy as np
a = np.array([1,2,3], dtype= 'int16')
print(a)


[1 2 3]


In [2]:
a

array([1, 2, 3])

print("Hello world")

In [3]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [4]:
b.ctypes


In [5]:
b.dtype

dtype('int32')

In [8]:
a.dtype

dtype('int16')

In [10]:
c = np.array([[[20,21],[22,23]],[[24,25],[26,27]]])
c.shape

(2, 2, 2)

In [11]:
c[0,0,1]

21

In [14]:
one = np.zeros([2,2], dtype= 'int32')

In [15]:
one

array([[0, 0],
       [0, 0]])

In [21]:
zero = np.ones_like([10])
zeronl = np.ones([2,10], dtype= 'int32')
zeronl

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [23]:
c.ones_like


AttributeError: 'numpy.ndarray' object has no attribute 'ones_like'

In [24]:
c = np.ones_like([2])
c

array([1])

In [25]:
np.ones_like(c)

array([1])

In [26]:
num = np.full([3,3],100)
num

array([[100, 100, 100],
       [100, 100, 100],
       [100, 100, 100]])

In [27]:
num = np.full_like(num,99)
num

array([[99, 99, 99],
       [99, 99, 99],
       [99, 99, 99]])

In [28]:
np.random.rand(4,2)

array([[0.75436179, 0.11749975],
       [0.12871421, 0.44404384],
       [0.92573645, 0.28491177],
       [0.54693543, 0.73477203]])

In [33]:
np.random.randint(7,size = [3,3])

array([[1, 0, 1],
       [4, 6, 5],
       [5, 0, 3]])

In [46]:
z = np.zeros([7,7], dtype='int16')
y = np.ones([5,5], dtype = 'int16')
print(z)
y[2,2] = 5
print(y)
z[1:6,1:6] = y
print(z)

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 5 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 0 0 0 0 0 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 1 1 5 1 1 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 0 0 0 0 0 0]]


In [58]:
filedata = np.genfromtxt("Sample_data.txt",delimiter=",")
filedata = filedata.astype('int32')
print(filedata)


[[     1      2      3      2      1      2      1   2121    321   1231
     432]
 [  4234 432432 414124   5325  63562   6324    312    312     31      2
    1231]
 [776344   6543      2     65      0   6340      4   3123   3123   3123
    3121]]
